name: "CI - Build and Push Docker image to GHCR"

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  REPOSITORY_IMAGE:  "${{ github.actor }}/${{ vars.IMAGE_NAME }}"

jobs:
  build-and-push:
    name: "Build and Push to GHCR"
    runs-on: ubuntu-latest
    outputs:
      tag-image: ${{ steps.meta.outputs.SHORT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: SHA Last Commit
        id: meta
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_IMAGE }}:${{ steps.meta.outputs.SHORT_SHA }}
            ghcr.io/${{ env.REPOSITORY_IMAGE }}:latest